---
title: "Future Addendum"
format: html
---

Did not have time to finish this section, will add details in the future. 


## GatingSet to FlowJo v10

Finally, there is one last area I would like to make everyone aware of. As we saw during [Week 05](/course/05_GatingSets/index.qmd), we were able to bring FlowJo .wsp files directly into GatingSet objects via the `CytoML` package. The opposite is also true, and we can convert our GatingSet objects from R into FlowJo .wsp that can be shared with a collaborator. 

The main challenge, is that the current implementation is underdocumented, and relies on an old docker container. [Docker]() is a software that will containerize everything that is needed to run something (in this particular case, an .exe file). However, the current version has not been updated recently at all. Likewise, installing Docker can be its own can of worms, especially from a IT safety side, so if your IT department was giving you hassles over Positron, Quarto or Git, then it is unlikely to happen. 

I have linked a walk-through of the process for anyone who is on their own computer and might be interested, as there are no other active instructions elsewhere as far as I know. 